route:
  group_by:
   - alertname
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: example@gmail.com
    from: example@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "example@gmail.com"
    auth_identity: "example@gmail.com"
    auth_password: "secret"