---
- name: Add prometheus configs
  copy:
    src: "{{ playbook_dir }}/../inventories/{{ deploy_environment }}/files/prometheus"
    dest: /volumns/
    directory_mode: yes
    owner: root
    group: root

- name: Add alertmanager configs
  copy:
    src: "{{ playbook_dir }}/../inventories/{{ deploy_environment }}/files/alertmanager"
    dest: /volumns/
    directory_mode: yes
    owner: root
    group: root
