---
- name: Create docker-ps-exporter
  docker_container:
    name: docker-ps-exporter
    image: "{{ registry_server | default('docker.io') }}/happiness9721/docker-ps-exporter"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    state: started
    recreate: yes
    restart_policy: always
    exposed_ports:
      - "{{ internal_port_docker_ps_exporter }}"
    ports:
      - "{{ exposed_port_docker_ps_exporter ~ ':' ~ internal_port_docker_ps_exporter }}"
    networks:
      - name: monitor_network

- name: Create cadvisor
  docker_container:
    name: cadvisor
    image: "{{ registry_server | default('docker.io') }}/google/cadvisor"
    command:
      - '--enable_load_reader=true'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    state: started
    recreate: yes
    restart_policy: always
    exposed_ports:
      - "{{ internal_port_cadvisor }}"
    ports:
      - "{{ exposed_port_cadvisor ~ ':' ~ internal_port_cadvisor }}"
    networks:
      - name: monitor_network

- name: Create node-exporter
  docker_container:
    name: node-exporter
    image: "{{ registry_server | default('docker.io') }}/prom/node-exporter"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    state: started
    recreate: yes
    restart_policy: always
    exposed_ports:
      - "{{ internal_port_node_exporter }}"
    ports:
      - "{{ exposed_port_node_exporter ~ ':' ~ internal_port_node_exporter }}"
    networks:
      - name: monitor_network
